FROM node:12

RUN mkdir -p /usr/src/bi-nextjs
WORKDIR /usr/src/bi-nextjs

RUN npm install -g yarn

# install dependencies
COPY package.json yarn.lock ./
# COPY patches ./patches
ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN yarn

EXPOSE 7007

CMD ["yarn","dev"]
